name: 'artifact2pr'
description: 'Upload build artifacts to a pull request'

branding:
  icon: 'upload'
  color: 'blue'

inputs:
  github-token: 
    description: 'GitHub token to use for authentication'
    required: true
    default: '${{ github.token }}'
  comment-heading:
    description: 'Heading for the comment'
    required: false
    default: '📦 **Build Artifacts**'
  comment-if-no-artifacts:
    description: 'Comment if no artifacts are found'
    required: false
    default: ''
    
runs:
  using: 'node20'
  main: 'dist/index.js'
