name: 'Artifact2PR'
description: 'Upload build artifacts to a pull request'

branding:
  icon: 'cloud-upload'
  color: 'blue'

inputs:
  github-token: 
    description: 'GitHub token to use for authentication'
    required: true
    default: '${{ github.token }}'
  comment-if-no-artifacts:
    description: 'Comment if no artifacts are found'
    required: false
    default: 'false'
    
runs:
  using: 'node20'
  main: 'dist/index.js'
