name: Update Major Release Tag

on:
  release:
    types: [published]

jobs:
  update-major:
    name: Update Major Release Tag
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && !github.event.release.draft }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Move major tag to new release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=${VERSION%%.*}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -fa "${MAJOR_VERSION}" -m "🔖 Update major version tag to $VERSION"
          git push origin "${MAJOR_VERSION}" --force
